# Generated by Django 2.2.1 on 2019-05-22 15:05

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('behance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='behanceproject',
            options={'verbose_name': 'Behance Project', 'verbose_name_plural': 'Behance Projects'},
        ),
        migrations.AddField(
            model_name='behanceproject',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='behanceproject',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='name'),
        ),
    ]
