# Generated by Django 2.2.1 on 2019-05-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('behance', '0002_auto_20190522_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='behanceproject',
            name='behance_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behanceproject',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='behanceproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
