# Generated by Django 2.2.1 on 2019-05-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('behance', '0003_auto_20190523_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehanceProjectModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=5)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='behance.BehanceProject')),
            ],
            options={
                'verbose_name': 'Behance Project Module',
                'verbose_name_plural': 'Behance Project Modules',
            },
        ),
    ]
