# Generated by Django 2.2.1 on 2019-05-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('behance', '0005_auto_20190523_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehanceProjectListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Behance Projects Listing Page',
                'verbose_name_plural': 'Behance Projects Listing Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='behanceproject',
            name='behance_id',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='behanceproject',
            name='behance_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='behanceproject',
            name='behance_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='BehanceProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='behance.BehanceProject')),
            ],
            options={
                'verbose_name': 'Behance Project Page',
                'verbose_name_plural': 'Behance Project Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
